
import { Translation, Language } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  en: {
    pageTitle: "Transaction Management",
    langLabel: "Language:",
    prevBalTitle: "Previous Balance",
    cashBalLabel: "Cash Balance",
    onlineBalLabel: "Online Balance",
    totalBalLabel: "Total Balance",
    incomeTitle: "Income Transactions",
    addIncomeBtn: "+ Add",
    incomeTypeHeader: "Income Type",
    amountHeader: "Amount",
    typeHeader: "Payment Type",
    actionHeader: "Action",
    detailsHeader: "Description",
    incomeTotalLabel: "Total Income:",
    expenseTitle: "Expense Transactions",
    addExpenseBtn: "+ Add",
    expenseTypeHeader: "Expense Type",
    expenseTotalLabel: "Total Expense:",
    finalBalanceTitle: "Final Balance (Prev + Income - Expense)",
    addIncomeTitle: "Add Income",
    editIncomeTitle: "Edit Income",
    addExpenseTitle: "Add Expense",
    editExpenseTitle: "Edit Expense",
    incomeTypeLabel: "Income Type",
    selectAccountLabel: "Select Account",
    amountLabel: "Amount (₹)",
    paymentLabel: "Payment Mode",
    customerOption: "Customer (Received from)",
    partnerOption: "Owner (Investment)",
    shopOption: "Shop Expense",
    labourOption: "Labour Payment",
    customOption: "Other Expense",
    cashOption: "Cash",
    onlineOption: "Online",
    bankOption: "Bank Transfer",
    submitBtn: "Save Transaction",
    updateBtn: "Update",
    cancelBtn: "Cancel",
    deleteBtn: "Delete",
    editBtn: "Edit",
    accountBalance: "Balance",
    dateSelectionTitle: "Date Filter",
    singleDayLabel: "Single Day",
    dateRangeLabel: "Date Range",
    transactionDateLabel: "Date:",
    fromDateLabel: "From:",
    toDateLabel: "To:",
    selectAccountPlaceholder: "Select Account",
    addNewAccount: "+ Add New Account",
    detailsLabel: "Description",
    selectPersonLabel: "Select Person",
    enterAccountName: "Enter Name:",
    confirmDelete: "Delete this record?",
    noIncome: "No income found",
    noExpense: "No expenses found",
    enableDateRange: "Apply for multiple days?",
    rangeEndDateLabel: "End Date:",
    rangeHelpText: "Adds this transaction to every day in range.",
    // Account Page
    tabTransactions: "Cashbook",
    tabAccounts: "Ledgers",
    tabLabour: "Labour",
    tabPartner: "Owners",
    searchPlaceholder: "Search...",
    totalReceivable: "Total Receivables",
    totalPayable: "Total Payables",
    netPosition: "Net Position",
    moneyIn: "Received",
    moneyOut: "Paid",
    attendanceSection: "Attendance",
    paymentSection: "Payments",
    totalDays: "Days",
    ratePerDay: "Rate/Day",
    totalPayableLabel: "Total Payable",
    totalPaidLabel: "Total Paid",
    balanceLabel: "Balance",
    statusPayable: "Payable",
    statusRecoverable: "Recoverable",
    backToAccounts: "← Back",
    addLabourAccount: "+ Add Labour",
    addPartnerAccount: "+ Add Owner",
    createAccountTitle: "New Account",
    accountCreated: "Created!",
    accountExists: "Exists already.",
    enterRate: "Rate (₹):",
    // Additional Account Localization
    partnerAccountLabel: "OWNER",
    noRecords: "No records found",
    labourCardLabel: "LABOUR",
    totalNetBalance: "Net Balance",
    monthDays: "Days",
    monthPayable: "Payable",
    monthPaid: "Paid",
    prevMonth: "< Prev",
    nextMonth: "Next >",
    dateHeader: "Date",
    statusHeader: "Status",
    workAmtHeader: "Amount",
    paymentDetailsHeader: "Details",
    sundayLabel: "(Sun)",
    paidPrefix: "Paid",
    noDaysInView: "No data.",
    noAccountsFound: "No accounts.",
    creatingLabourAccount: "New Labour Account",
    creatingPartnerAccount: "New Owner Account",
    nameLabel: "Account Holder",
    createBtn: "Create",
    payLabourBtn: "Pay / Advance",
    addBonusBtn: "+ Extra Payable",
    adjustmentTitle: "Add Extra Payable (Bonus/Arrears)",
    adjustmentAmount: "Amount (to Add to Payable)",
    adjustmentNote: "Reason (e.g. Bonus, Overtime)",
    // Stats
    statsTitle: "Summary Report",
    statsDateLabel: "From",
    tillNow: "Till Now",
    statsTotalExpense: "Total Expense",
    statsLabourExpense: "Labour Paid",
    statsPartnerIncome: "Investments",
    statsLabourPerQuintal: "Labour Cost / Quintal",
    totalDispatchedLabel: "Total Dispatched",
    statsOilExpense: "Total Oil Expense",
    oilOption: "Oil / Fuel",
    electricityOption: "Electricity Bill",
    statsElectricityExpense: "Electricity Bill",
    viewDetailedReport: "View Detailed Transactions",
    hideDetailedReport: "Hide Transactions",
    detailedTransactionReport: "Detailed Transaction Report",
    translateBtn: "Translate View",
    translating: "Translating...",
    // Stock
    tabStock: "Stock & Sales",
    tabStockDashboard: "Dashboard",
    tabCustomers: "Customers",
    tabSuppliers: "Suppliers",
    currentStockTitle: "Current Stock",
    addStockBtn: "+ Add",
    subtractStockBtn: "- Sub",
    unitToggleLabel: "Unit:",
    dispatchTitle: "Dispatch Stock (Bill Generation)",
    vehicleNoLabel: "Vehicle No",
    quantityLabel: "Quantity",
    rateLabel: "Rate",
    convertedWeightLabel: "In KG:",
    totalPriceLabel: "Bill Amount:",
    dispatchBtn: "Generate Bill & Dispatch",
    stockHistoryTitle: "Movement History",
    colGadi: "Vehicle",
    colQty: "Qty",
    colRate: "Rate",
    colRemaining: "Stock",
    lowStockWarning: "Low Stock!",
    adjustStockTitle: "Manual Adjust",
    stockAdded: "Added",
    stockSubtracted: "Subtracted",
    stockDispatched: "Bill Generated & Stock Dispatched",
    viewHistoryBtn: "📜 View History",
    historyModalTitle: "Detailed Stock Ledger",
    colPrevStock: "Prev Stock",
    colChange: "Change (+/-)",
    colNewStock: "Remaining",
    // Opening Balance
    editOpeningBalanceTitle: "Opening Balance",
    initialCashLabel: "Cash:",
    initialOnlineLabel: "Online:",
    saveBtn: "Save",
    // Customer View
    tabCustomer: "Customers (Receivables)",
    customerTotalStock: "Total Stock Given",
    customerTotalBilled: "Total Billed",
    customerTotalReceived: "Total Received",
    customerBalance: "Outstanding Balance",
    colBilled: "Bill Amount",
    colReceived: "Received",
    colVehicle: "Details",
    viewStatement: "Ledger Statement",
    viewDetails: "Stock Details",
    totalDebit: "Total Billed",
    totalCredit: "Total Received",
    colDebit: "Debit",
    colCredit: "Credit",
    colBalance: "Balance",
    dr: "Rs",
    cr: "Rs",
    
    // Reports
    tabReports: "Reports",
    reportAllTransactionsTitle: "All Transactions",
    filterTypeLabel: "Filter by Type",
    filterAll: "All Transactions",
    filterIncome: "Income Only",
    filterExpense: "Expense Only",
    reportTotalIncome: "Total Income",
    reportTotalExpense: "Total Expense",
    reportNet: "Net Balance",

    // Supplier
    tabSupplier: "Suppliers",
    addSupplierAccount: "+ Add Supplier",
    creatingSupplierAccount: "Creating Supplier Account",
    colPaymentMade: "Payment Made (Dr)",
    colRefundReceived: "Adv/Refund (Cr)",
    totalPaidToSupplier: "Total Paid",
    totalReceivedFromSupplier: "Total Refunded/Adv",
    netPaidBalance: "Net Paid",
    receiveRefundBtn: "Receive Refund / Advance",
    supplierCreditModalTitle: "Receive Money from Supplier",
    supplierCreditHelp: "This will be recorded as Income/Credit",
    supplierOption: "Supplier (Payment/Refund)",

    // New Keys
    unitKg: "KG",
    unitQuintal: "Quintal",
    alertInvalidQty: "Invalid Quantity",
    alertEnterQtyAdd: "Enter valid quantity",
    alertEnterQtySub: "Enter valid quantity",
    alertInsufficientStock: "Insufficient Stock!",
    alertAmountRequired: "Amount required",
    alertDateOrder: "Start date must be before end date",
    editStockEntryTitle: "Edit Stock Entry",
    manualAddNote: "Manual Add",
    manualSubNote: "Manual Sub",
    transactionHistory: "Transaction History",
    addCustomerAccount: "+ Add Customer",
    creatingCustomerAccount: "Creating Customer Account",
    dispatchTypeLabel: "DISPATCH",
    
    // Strictly Isolated Labels
    operationalExpenseLabel: "Operational Expense",
    supplierPaymentsLabel: "Supplier Payments",
    sourceExpense: "Source: Expense",
    sourceManual: "Source: Manual",

    // Conversion
    cashConversionOption: "Online -> Cash (Transfer)",

    downloadPdfBtn: "Download PDF",
    
    hisaabHelp: "Double click date to mark Hisaab",

    // Validation
    errRequired: "Required",
    errAccountRequired: "Please select an account",
    errPositiveAmount: "Must be > 0"
  },
  hi: {
    pageTitle: "लेनदेन प्रबंधन",
    langLabel: "भाषा:",
    prevBalTitle: "पिछला शेष",
    cashBalLabel: "नकद शेष",
    onlineBalLabel: "ऑनलाइन शेष",
    totalBalLabel: "कुल शेष",
    incomeTitle: "आय लेनदेन",
    addIncomeBtn: "+ जोड़ें",
    incomeTypeHeader: "आय का प्रकार",
    amountHeader: "राशि",
    typeHeader: "माध्यम",
    actionHeader: "कार्य",
    detailsHeader: "विवरण",
    incomeTotalLabel: "कुल आय:",
    expenseTitle: "खर्च लेनदेन",
    addExpenseBtn: "+ जोड़ें",
    expenseTypeHeader: "खर्च का प्रकार",
    expenseTotalLabel: "कुल खर्च:",
    finalBalanceTitle: "अंतिम शेष (रोकड़)",
    addIncomeTitle: "आय जोड़ें",
    editIncomeTitle: "आय संपादित करें",
    addExpenseTitle: "खर्च जोड़ें",
    editExpenseTitle: "खर्च संपादित करें",
    incomeTypeLabel: "आय का प्रकार",
    selectAccountLabel: "खाता चुनें",
    amountLabel: "राशि (₹)",
    paymentLabel: "भुगतान माध्यम",
    customerOption: "ग्राहक (प्राप्त हुआ)",
    partnerOption: "मालिक (निवेश)",
    shopOption: "दुकान खर्च",
    labourOption: "मजदूरी भुगतान",
    customOption: "अन्य खर्च",
    cashOption: "नकद",
    onlineOption: "ऑनलाइन",
    bankOption: "बैंक",
    submitBtn: "सहेजें",
    updateBtn: "अपडेट",
    cancelBtn: "रद्द",
    deleteBtn: "हटाएं",
    editBtn: "संपादित",
    accountBalance: "शेष",
    dateSelectionTitle: "तारीख चुनें",
    singleDayLabel: "एक दिन",
    dateRangeLabel: "रेंज",
    transactionDateLabel: "तारीख:",
    fromDateLabel: "से:",
    toDateLabel: "तक:",
    selectAccountPlaceholder: "खाता चुनें",
    addNewAccount: "+ नया खाता",
    detailsLabel: "विवरण",
    selectPersonLabel: "व्यक्ति चुनें",
    enterAccountName: "नाम लिखें:",
    confirmDelete: "हटाना सुनिश्चित करें?",
    noIncome: "कोई आय नहीं",
    noExpense: "कोई खर्च नहीं",
    enableDateRange: "रेंज में लागू करें?",
    rangeEndDateLabel: "अंतिम तारीख:",
    rangeHelpText: "यह हर दिन के लिए जोड़ा जाएगा।",
    tabTransactions: "रोकड़ बही",
    tabAccounts: "खाते (Ledger)",
    tabLabour: "मजदूर",
    tabPartner: "मालिक",
    searchPlaceholder: "खोजें...",
    totalReceivable: "कुल लेना है",
    totalPayable: "कुल देना है",
    netPosition: "शुद्ध स्थिति",
    moneyIn: "प्राप्त",
    moneyOut: "भुगतान",
    attendanceSection: "हाजिरी",
    paymentSection: "भुगतान",
    totalDays: "दिन",
    ratePerDay: "दर/दिन",
    totalPayableLabel: "कुल वेतन",
    totalPaidLabel: "कुल दिया",
    balanceLabel: "शेष",
    statusPayable: "देना है",
    statusRecoverable: "लेना है",
    backToAccounts: "← वापस",
    addLabourAccount: "+ मजदूर",
    addPartnerAccount: "+ मालिक",
    createAccountTitle: "नया खाता",
    accountCreated: "बन गया!",
    accountExists: "पहले से मौजूद है।",
    enterRate: "दर (₹):",
    partnerAccountLabel: "मालिक",
    noRecords: "रिकॉर्ड नहीं",
    labourCardLabel: "मजदूर",
    totalNetBalance: "कुल शेष",
    monthDays: "दिन",
    monthPayable: "वेतन",
    monthPaid: "दिया",
    prevMonth: "< पिछला",
    nextMonth: "अगला >",
    dateHeader: "तारीख",
    statusHeader: "स्थिति",
    workAmtHeader: "राशि",
    paymentDetailsHeader: "विवरण",
    sundayLabel: "(रवि)",
    paidPrefix: "दिया",
    noDaysInView: "डाटा नहीं",
    noAccountsFound: "खाते नहीं मिले",
    creatingLabourAccount: "नया मजदूर खाता",
    creatingPartnerAccount: "नया मालिक खाता",
    nameLabel: "खाता धारक",
    createBtn: "बनाएं",
    payLabourBtn: "भुगतान / एडवांस",
    addBonusBtn: "+ एक्स्ट्रा/बोनस",
    adjustmentTitle: "अतिरिक्त भुगतान जोड़ें (बोनस/पिछला बकाया)",
    adjustmentAmount: "राशि (वेतन में जोड़ने के लिए)",
    adjustmentNote: "कारण (जैसे बोनस, ओवरटाइम)",
    statsTitle: "सारांश रिपोर्ट",
    statsDateLabel: "तारीख से",
    tillNow: "अब तक",
    statsTotalExpense: "कुल खर्च",
    statsLabourExpense: "मजदूरी दी",
    statsPartnerIncome: "निवेश",
    statsLabourPerQuintal: "मजदूरी दर / क्विंटल",
    totalDispatchedLabel: "कुल डिस्पैच",
    statsOilExpense: "कुल तेल खर्च",
    oilOption: "तेल / ईंधन",
    electricityOption: "बिजली बिल",
    statsElectricityExpense: "बिजली बिल खर्च",
    viewDetailedReport: "विस्तृत लेनदेन देखें",
    hideDetailedReport: "लेनदेन छुपाएं",
    detailedTransactionReport: "विस्तृत लेनदेन रिपोर्ट",
    translateBtn: "डेटा अनुवाद करें",
    translating: "अनुवाद हो रहा है...",
    tabStock: "स्टॉक और बिक्री",
    tabStockDashboard: "डैशबोर्ड",
    tabCustomers: "ग्राहक",
    tabSuppliers: "सप्लायर",
    currentStockTitle: "स्टॉक",
    addStockBtn: "+ जोड़ें",
    subtractStockBtn: "- घटाएं",
    unitToggleLabel: "इकाई:",
    dispatchTitle: "स्टॉक डिस्पैच (बिल बनाएं)",
    vehicleNoLabel: "गाड़ी नं",
    quantityLabel: "मात्रा",
    rateLabel: "दर",
    convertedWeightLabel: "किग्रा:",
    totalPriceLabel: "बिल राशि:",
    dispatchBtn: "बिल बनाएं और भेजें",
    stockHistoryTitle: "इतिहास",
    colGadi: "गाड़ी",
    colQty: "मात्रा",
    colRate: "दर",
    colRemaining: "स्टॉक",
    lowStockWarning: "स्टॉक कम है!",
    adjustStockTitle: "मैनुअल",
    stockAdded: "जोड़ा गया",
    stockSubtracted: "घटाया गया",
    stockDispatched: "बिल बना और डिस्पैच हुआ",
    viewHistoryBtn: "📜 स्टॉक हिसाब देखें",
    historyModalTitle: "विस्तृत स्टॉक लेजर",
    colPrevStock: "पिछला स्टॉक",
    colChange: "बदलाव (+/-)",
    colNewStock: "बचा स्टॉक",
    editOpeningBalanceTitle: "शुरुआती शेष",
    initialCashLabel: "नकद:",
    initialOnlineLabel: "ऑनलाइन:",
    saveBtn: "सहेजें",
    tabCustomer: "ग्राहक (उधारी)",
    customerTotalStock: "कुल माल दिया",
    customerTotalBilled: "कुल बिल",
    customerTotalReceived: "कुल प्राप्त",
    customerBalance: "बकाया राशि",
    colBilled: "बिल (Dr)",
    colReceived: "प्राप्त (Cr)",
    colVehicle: "विवरण",
    viewStatement: "हिसाब पर्चा",
    viewDetails: "स्टॉक विवरण",
    totalDebit: "कुल डेबिट",
    totalCredit: "कुल क्रेडिट",
    colDebit: "नाम",
    colCredit: "जमा",
    colBalance: "शेष",
    dr: "Rs",
    cr: "Rs",
    
    // Reports
    tabReports: "रिपोर्ट",
    reportAllTransactionsTitle: "सभी लेनदेन",
    filterTypeLabel: "प्रकार चुनें",
    filterAll: "सभी लेनदेन",
    filterIncome: "केवल आय",
    filterExpense: "केवल खर्च",
    reportTotalIncome: "कुल आय",
    reportTotalExpense: "कुल खर्च",
    reportNet: "शुद्ध शेष",

    // Supplier
    tabSupplier: "सप्लायर",
    addSupplierAccount: "+ सप्लायर जोड़ें",
    creatingSupplierAccount: "नया सप्लायर खाता",
    colPaymentMade: "भुगतान किया (Dr)",
    colRefundReceived: "वापसी/एडवांस (Cr)",
    totalPaidToSupplier: "कुल भुगतान",
    totalReceivedFromSupplier: "कुल वापसी",
    netPaidBalance: "शुद्ध भुगतान",
    receiveRefundBtn: "वापसी / एडवांस प्राप्त करें",
    supplierCreditModalTitle: "सप्लायर से पैसा प्राप्त",
    supplierCreditHelp: "यह आय/क्रेडिट के रूप में दर्ज होगा",
    supplierOption: "सप्लायर (भुगतान/वापसी)",

    // New Keys
    unitKg: "KG",
    unitQuintal: "Quintal",
    alertInvalidQty: "अमान्य मात्रा",
    alertEnterQtyAdd: "सही मात्रा दर्ज करें",
    alertEnterQtySub: "सही मात्रा दर्ज करें",
    alertInsufficientStock: "स्टॉक कम है!",
    alertAmountRequired: "राशि आवश्यक है",
    alertDateOrder: "तारीख सही चुनें",
    editStockEntryTitle: "स्टॉक एंट्री संपादित करें",
    manualAddNote: "मैनुअल जोड़ा",
    manualSubNote: "मैनुअल घटाया",
    transactionHistory: "लेनदेन इतिहास",
    addCustomerAccount: "+ ग्राहक जोड़ें",
    creatingCustomerAccount: "नया ग्राहक खाता",
    dispatchTypeLabel: "DISPATCH",
    
    // Strictly Isolated Labels
    operationalExpenseLabel: "दुकान/मजदूरी खर्च",
    supplierPaymentsLabel: "सप्लायर भुगतान",
    sourceExpense: "स्रोत: खर्च",
    sourceManual: "स्रोत: मैनुअल",
    
    // Conversion
    cashConversionOption: "ऑनलाइन -> कैश (निकासी)",
    
    downloadPdfBtn: "PDF डाउनलोड करें",
    
    hisaabHelp: "हिसाब के लिए तारीख पर डबल क्लिक करें",

    // Validation
    errRequired: "अनिवार्य",
    errAccountRequired: "खाता चुनें",
    errPositiveAmount: "राशि > 0 होनी चाहिए"
  },
  pa: {
    pageTitle: "ਲੈਣ-ਦੇਣ ਪ੍ਰਬੰਧਨ",
    langLabel: "ਭਾਸ਼ਾ:",
    prevBalTitle: "ਪਿਛਲਾ ਬਕਾਇਆ",
    cashBalLabel: "ਨਕਦ ਬਕਾਇਆ",
    onlineBalLabel: "ਔਨਲਾਈਨ ਬਕਾਇਆ",
    totalBalLabel: "ਕੁੱਲ ਬਕਾਇਆ",
    incomeTitle: "ਆਮਦਨ ਲੈਣ-ਦੇਣ",
    addIncomeBtn: "+ ਜੋੜੋ",
    incomeTypeHeader: "ਆਮਦਨ ਦੀ ਕਿਸਮ",
    amountHeader: "ਰਕਮ",
    typeHeader: "ਭੁਗਤਾਨ ਕਿਸਮ",
    actionHeader: "ਕਾਰਵਾਈ",
    detailsHeader: "ਵੇਰਵਾ",
    incomeTotalLabel: "ਕੁੱਲ ਆਮਦਨ:",
    expenseTitle: "ਖਰਚੇ ਲੈਣ-ਦੇਣ",
    addExpenseBtn: "+ ਜੋੜੋ",
    expenseTypeHeader: "ਖਰਚੇ ਦੀ ਕਿਸਮ",
    expenseTotalLabel: "ਕੁੱਲ ਖਰਚਾ:",
    finalBalanceTitle: "ਅੰਤਿਮ ਬਕਾਇਆ",
    addIncomeTitle: "ਆਮਦਨ ਜੋੜੋ",
    editIncomeTitle: "ਆਮਦਨ ਸੋਧੋ",
    addExpenseTitle: "ਖਰਚਾ ਜੋੜੋ",
    editExpenseTitle: "ਖਰਚਾ ਸੋਧੋ",
    incomeTypeLabel: "ਆਮਦਨ ਦੀ ਕਿਸਮ",
    selectAccountLabel: "ਖਾਤਾ ਚੁਣੋ",
    amountLabel: "ਰਕਮ (₹)",
    paymentLabel: "ਭੁਗਤਾਨ ਕਿਸਮ",
    customerOption: "ਗਾਹਕ (ਪ੍ਰਾਪਤ ਹੋਇਆ)",
    partnerOption: "ਮਾਲਕ (ਨਿਵੇਸ਼)",
    shopOption: "ਦੁਕਾਨ ਖਰਚਾ",
    labourOption: "ਮਜ਼ਦੂਰੀ ਭੁਗਤਾਨ",
    customOption: "ਹੋਰ ਖਰਚਾ",
    cashOption: "ਨਕਦ",
    onlineOption: "ਔਨਲਾਈਨ",
    bankOption: "ਬੈਂਕ",
    submitBtn: "ਸੇਵ ਕਰੋ",
    updateBtn: "ਅਪਡੇਟ",
    cancelBtn: "ਰੱਦ",
    deleteBtn: "ਮਿਟਾਓ",
    editBtn: "ਸੋਧੋ",
    accountBalance: "ਬਕਾਇਆ",
    dateSelectionTitle: "ਤਾਰੀਖ ਚੁਣੋ",
    singleDayLabel: "ਇੱਕ ਦਿਨ",
    dateRangeLabel: "ਸੀਮਾ",
    transactionDateLabel: "ਤਾਰੀਖ:",
    fromDateLabel: "ਤੋਂ:",
    toDateLabel: "ਤੱਕ:",
    selectAccountPlaceholder: "ਖਾਤਾ ਚੁਣੋ",
    addNewAccount: "+ ਨਵਾਂ ਖਾਤਾ",
    detailsLabel: "ਵੇਰਵਾ",
    selectPersonLabel: "ਵਿਅਕਤੀ ਚੁਣੋ",
    enterAccountName: "ਨਾਮ ਦਰਜ ਕਰੋ:",
    confirmDelete: "ਮਿਟਾਉਣਾ ਯਕੀਨੀ ਹੈ?",
    noIncome: "ਕੋਈ ਆਮਦਨ ਨਹੀਂ",
    noExpense: "ਕੋਈ ਖਰਚਾ ਨਹੀਂ",
    enableDateRange: "ਸੀਮਾ ਵਿੱਚ ਲਾਗੂ ਕਰੋ?",
    rangeEndDateLabel: "ਅੰਤਿਮ ਤਾਰੀਖ:",
    rangeHelpText: "ਇਹ ਹਰ ਦਿਨ ਲਈ ਜੋੜਿਆ ਜਾਵੇਗਾ।",
    tabTransactions: "ਰੋਕੜ ਵਹੀ",
    tabAccounts: "ਖਾਤੇ (Ledger)",
    tabLabour: "ਮਜ਼ਦੂਰ",
    tabPartner: "ਮਾਲਕ",
    searchPlaceholder: "ਖੋਜੋ...",
    totalReceivable: "ਕੁੱਲ ਲੈਣਯੋਗ",
    totalPayable: "ਕੁੱਲ ਦੇਣਦਾਰੀ",
    netPosition: "ਸ਼ੁੱਧ ਸਥਿਤੀ",
    moneyIn: "ਪ੍ਰਾਪਤ",
    moneyOut: "ਭੁਗਤਾਨ",
    attendanceSection: "ਹਾਜ਼ਰੀ",
    paymentSection: "ਭੁਗਤਾਨ",
    totalDays: "ਦਿਨ",
    ratePerDay: "ਰੇਟ/ਦਿਨ",
    totalPayableLabel: "ਕੁੱਲ ਤਨਖਾਹ",
    totalPaidLabel: "ਕੁੱਲ ਦਿੱਤਾ",
    balanceLabel: "ਬਕਾਇਆ",
    statusPayable: "ਦੇਣਾ ਹੈ",
    statusRecoverable: "ਲੈਣਾ ਹੈ",
    backToAccounts: "← ਵਾਪਸ",
    addLabourAccount: "+ ਮਜ਼ਦੂਰ",
    addPartnerAccount: "+ ਮਾਲਕ",
    createAccountTitle: "ਨਵਾਂ ਖਾਤਾ",
    accountCreated: "ਬਣ ਗਿਆ!",
    accountExists: "ਪਹਿਲਾਂ ਹੀ ਮੌਜੂਦ ਹੈ।",
    enterRate: "ਰੇਟ (₹):",
    partnerAccountLabel: "ਮਾਲਕ",
    noRecords: "ਕੋਈ ਰਿਕਾਰਡ ਨਹੀਂ",
    labourCardLabel: "ਮਜ਼ਦੂਰ",
    totalNetBalance: "ਕੁੱਲ ਬਕਾਇਆ",
    monthDays: "ਦਿਨ",
    monthPayable: "ਤਨਖਾਹ",
    monthPaid: "ਦਿੱਤਾ",
    prevMonth: "< ਪਿਛਲਾ",
    nextMonth: "ਅਗਲਾ >",
    dateHeader: "ਤਾਰੀਖ",
    statusHeader: "ਸਥਿਤੀ",
    workAmtHeader: "ਰਕਮ",
    paymentDetailsHeader: "ਵੇਰਵਾ",
    sundayLabel: "(ਐਤ)",
    paidPrefix: "ਦਿੱਤਾ",
    noDaysInView: "ਕੋਈ ਡਾਟਾ ਨਹੀਂ",
    noAccountsFound: "ਕੋਈ ਖਾਤਾ ਨਹੀਂ",
    creatingLabourAccount: "ਨਵਾਂ ਮਜ਼ਦੂਰ ਖਾਤਾ",
    creatingPartnerAccount: "ਨਵਾਂ ਮਾਲਕ ਖਾਤਾ",
    nameLabel: "ਖਾਤਾ ਧਾਰਕ",
    createBtn: "ਬਣਾਓ",
    payLabourBtn: "ਭੁਗਤਾਨ / ਐਡਵਾਂਸ",
    addBonusBtn: "+ ਐਕਸਟਰਾ/ਬੋਨਸ",
    adjustmentTitle: "ਵਾਧੂ ਭੁਗਤਾਨ ਸ਼ਾਮਲ ਕਰੋ (ਬੋਨਸ/ਬਕਾਇਆ)",
    adjustmentAmount: "ਰਕਮ (ਵੇਤਨ ਵਿੱਚ ਜੋੜਨ ਲਈ)",
    adjustmentNote: "ਕਾਰਨ (ਜਿਵੇਂ ਬੋਨਸ, ਓਵਰਟਾਈਮ)",
    statsTitle: "ਸੰਖੇਪ ਰਿਪੋਰਟ",
    statsDateLabel: "ਮਿਤੀ ਤੋਂ",
    tillNow: "ਅੱਜ ਤੱਕ",
    statsTotalExpense: "ਕੁੱਲ ਖਰਚੇ",
    statsLabourExpense: "ਮਜ਼ਦੂਰੀ ਦਿੱਤੀ",
    statsPartnerIncome: "ਨਿਵੇਸ਼",
    statsLabourPerQuintal: "ਮਜ਼ਦੂਰੀ / ਕਵਿੰਟਲ",
    totalDispatchedLabel: "ਕੁੱਲ ਡਿਸਪੈਚ",
    statsOilExpense: "ਕੁੱਲ ਤੇਲ ਖਰਚਾ",
    oilOption: "ਤੇਲ / ਬਾਲਣ",
    electricityOption: "ਬਿਜਲੀ ਦਾ ਬਿੱਲ",
    statsElectricityExpense: "ਬਿਜਲੀ ਖਰਚਾ",
    viewDetailedReport: "ਵੇਰਵੇ ਸਹਿਤ ਲੈਣ-ਦੇਣ ਦੇਖੋ",
    hideDetailedReport: "ਲੈਣ-ਦੇਣ ਲੁਕਾਓ",
    detailedTransactionReport: "ਵੇਰਵੇ ਸਹਿਤ ਲੈਣ-ਦੇਣ ਰਿਪੋਰਟ",
    translateBtn: "ਡਾਟਾ ਅਨੁਵਾਦ ਕਰੋ",
    translating: "ਅਨੁਵਾਦ ਹੋ ਰਿਹਾ ਹੈ...",
    tabStock: "ਸਟਾਕ ਅਤੇ ਵਿਕਰੀ",
    tabStockDashboard: "ਡੈਸ਼ਬੋਰਡ",
    tabCustomers: "ਗਾਹਕ",
    tabSuppliers: "ਸਪਲਾਇਰ",
    currentStockTitle: "ਸਟਾਕ",
    addStockBtn: "+ ਜੋੜੋ",
    subtractStockBtn: "- ਘਟਾਓ",
    unitToggleLabel: "ਯੂਨਿਟ:",
    dispatchTitle: "ਸਟਾਕ ਡਿਸਪੈਚ (बिल बनाएं)",
    vehicleNoLabel: "ਗੱਡੀ ਨੰਬਰ",
    quantityLabel: "ਮਾਤਰਾ",
    rateLabel: "ਰੇਟ",
    convertedWeightLabel: "ਕਿਲੋਗ੍ਰਾਮ:",
    totalPriceLabel: "ਬਿੱਲ ਰਕਮ:",
    dispatchBtn: "ਬਿੱਲ ਬਣਾਓ ਅਤੇ ਭੇਜੋ",
    stockHistoryTitle: "ਇਤਿਹਾਸ",
    colGadi: "ਗੱਡੀ",
    colQty: "ਮਾਤਰਾ",
    colRate: "ਰੇਟ",
    colRemaining: "ਸਟਾਕ",
    lowStockWarning: "ਸਟਾਕ ਘੱਟ ਹੈ!",
    adjustStockTitle: "ਮੈਨੁਅਲ",
    stockAdded: "ਜੋੜਿਆ",
    stockSubtracted: "ਘਟਾਇਆ",
    stockDispatched: "ਬਿੱਲ ਬਣਿਆ ਅਤੇ ਭੇਜਿਆ",
    viewHistoryBtn: "📜 ਸਟਾਕ ਵੇਰਵਾ ਦੇਖੋ",
    historyModalTitle: "ਵਿਸਤ੍ਰਿਤ ਸਟਾਕ ਲੇਜ਼ਰ",
    colPrevStock: "पिछला स्टॉक",
    colChange: "ਤਬਦੀਲੀ",
    colNewStock: "ਬਾਕੀ ਸਟਾਕ",
    editOpeningBalanceTitle: "ਸ਼ੁਰੂਆਤੀ ਬਕਾਇਆ",
    initialCashLabel: "ਨਕਦ:",
    initialOnlineLabel: "ਔਨਲਾਈਨ:",
    saveBtn: "ਸੇਵ",
    tabCustomer: "ਗਾਹਕ (ਉਧਾਰੀ)",
    customerTotalStock: "ਕੁੱਲ ਮਾਲ ਦਿੱਤਾ",
    customerTotalBilled: "ਕੁੱਲ ਬਿੱਲ (Dr)",
    customerTotalReceived: "ਕੁੱਲ ਪ੍ਰਾਪਤ (Cr)",
    customerBalance: "ਬਕਾਇਆ ਰਕਮ",
    colBilled: "ਬਿੱਲ (Dr)",
    colReceived: "ਪ੍ਰਾਪਤ (Cr)",
    colVehicle: "ਵੇਰਵਾ",
    viewStatement: "ਹਿਸਾਬ ਪਰਚਾ",
    viewDetails: "ਸਟਾਕ ਵੇਰਵਾ",
    totalDebit: "ਕੁੱਲ ਡੈਬਿਟ (ਉਧਾਰ)",
    totalCredit: "ਕੁੱਲ ਕ੍ਰੈਡਿਟ (ਜਮ੍ਹਾ)",
    colDebit: "ਡੈਬਿਟ (Dr)",
    colCredit: "ਕ੍ਰੈਡਿਟ (Cr)",
    colBalance: "ਬਕਾਇਆ",
    dr: "Rs",
    cr: "Rs",
    
    // Reports
    tabReports: "ਰਿਪੋਰਟਾਂ",
    reportAllTransactionsTitle: "ਸਾਰੇ ਲੈਣ-ਦੇਣ",
    filterTypeLabel: "ਕਿਸਮ ਚੁਣੋ",
    filterAll: "ਸਾਰੇ ਲੈਣ-ਦੇਣ",
    filterIncome: "ਕੇਵਲ ਆਮਦਨ",
    filterExpense: "ਕੇਵਲ ਖਰਚਾ",
    reportTotalIncome: "ਕੁੱਲ ਆਮਦਨ",
    reportTotalExpense: "ਕੁੱਲ ਖਰਚਾ",
    reportNet: "ਸ਼ੁੱਧ ਬਕਾਇਆ",

    // Supplier
    tabSupplier: "ਸਪਲਾਇਰ",
    addSupplierAccount: "+ ਸਪਲਾਇਰ ਜੋੜੋ",
    creatingSupplierAccount: "ਨਵਾਂ ਸਪਲਾਇਰ ਖਾਤਾ",
    colPaymentMade: "ਭੁਗਤਾਨ ਕੀਤਾ (Dr)",
    colRefundReceived: "ਵਾਪਸੀ/ਐਡਵਾਂਸ (Cr)",
    totalPaidToSupplier: "ਕੁੱਲ ਭੁਗਤਾਨ",
    totalReceivedFromSupplier: "ਕੁੱਲ ਵਾਪਸੀ",
    netPaidBalance: "ਸ਼ੁੱਧ ਭੁਗਤਾਨ",
    receiveRefundBtn: "ਵਾਪਸੀ / ਐਡਵਾਂਸ ਪ੍ਰਾਪਤ ਕਰੋ",
    supplierCreditModalTitle: "ਸਪਲਾਇਰ ਤੋਂ ਪੈਸੇ ਪ੍ਰਾਪਤ",
    supplierCreditHelp: "ਇਹ ਆਮਦਨ/ਕ੍ਰੈਡਿਟ ਵਜੋਂ ਦਰਜ ਹੋਵੇਗਾ",
    supplierOption: "ਸਪਲਾਇਰ (ਭੁਗਤਾਨ/ਵਾਪਸੀ)",

    // New Keys
    unitKg: "ਕਿਲੋ",
    unitQuintal: "ਕਵਿੰਟਲ",
    alertInvalidQty: "ਗਲਤ ਮਾਤਰਾ",
    alertEnterQtyAdd: "ਸਹੀ ਮਾਤਰਾ ਦਰਜ ਕਰੋ",
    alertEnterQtySub: "ਸਹੀ ਮਾਤਰਾ ਦਰਜ ਕਰੋ",
    alertInsufficientStock: "ਸਟਾਕ ਘੱਟ ਹੈ!",
    alertAmountRequired: "ਰਕਮ ਲੋੜੀਂਦੀ ਹੈ",
    alertDateOrder: "ਤਾਰੀਖ ਸਹੀ ਚੁਣੋ",
    editStockEntryTitle: "ਸਟਾਕ ਐਂਟਰੀ ਸੋਧੋ",
    manualAddNote: "ਮੈਨੁਅਲ ਜੋੜ",
    manualSubNote: "ਮੈਨੁਅਲ ਘਟਾਓ",
    transactionHistory: "ਲੈਣ-ਦੇਣ ਇਤਿਹਾਸ",
    addCustomerAccount: "+ ਗਾਹਕ ਜੋੜੋ",
    creatingCustomerAccount: "ਨਵਾਂ ਗਾਹਕ ਖਾਤਾ",
    dispatchTypeLabel: "ਡਿਸਪੈਚ",
    
    // Strictly Isolated Labels
    operationalExpenseLabel: "ਦੁਕਾਨ/ਮਜ਼ਦੂਰੀ ਖਰਚ",
    supplierPaymentsLabel: "ਸਪਲਾਇਰ ਭੁਗਤਾਨ",
    sourceExpense: "ਸਰੋਤ: ਖਰਚਾ",
    sourceManual: "ਸਰੋਤ: ਮੈਨੁਅਲ",
    
    // Conversion
    cashConversionOption: "ਔਨਲਾਈਨ -> ਨਕਦ (ਕਢਵਾਉਣਾ)",

    downloadPdfBtn: "PDF ਡਾਊਨਲੋਡ ਕਰੋ",

    hisaabHelp: "ਹਿਸਾਬ ਲਈ ਤਾਰੀਖ 'ਤੇ ਡਬਲ ਕਲਿੱਕ ਕਰੋ",

    // Validation
    errRequired: "ਲੋੜੀਂਦਾ",
    errAccountRequired: "ਖਾਤਾ ਚੁਣੋ",
    errPositiveAmount: "ਰਕਮ > 0 ਹੋਣੀ ਚਾਹੀਦੀ ਹੈ"
  }
};
