
-- Complete database schema for Supabase Project 2
-- Run this in the Supabase SQL Editor

-- 1. Transactions Table
create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  type text not null check (type in ('income', 'expense')),
  category text not null,
  account_name text,
  details text,
  amount numeric not null check (amount > 0),
  payment_type text not null,
  date date not null,
  timestamp bigint not null,
  created_at timestamptz default now()
);

create index if not exists idx_transactions_user_id
  on public.transactions (user_id);

alter table public.transactions enable row level security;

create policy "transactions_select_own"
  on public.transactions for select
  using (auth.uid() = user_id);

create policy "transactions_insert_own"
  on public.transactions for insert
  with check (auth.uid() = user_id);

create policy "transactions_update_own"
  on public.transactions for update
  using (auth.uid() = user_id);

create policy "transactions_delete_own"
  on public.transactions for delete
  using (auth.uid() = user_id);


-- 2. Accounts Table
create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  type text not null,
  rate numeric,
  phone text,
  address text,
  acres numeric,
  date_cutter date,
  created_at timestamptz default now(),
  unique (user_id, name)
);

create index if not exists idx_accounts_user_id
  on public.accounts (user_id);

alter table public.accounts enable row level security;

create policy "accounts_select_own"
  on public.accounts for select
  using (auth.uid() = user_id);

create policy "accounts_insert_own"
  on public.accounts for insert
  with check (auth.uid() = user_id);

create policy "accounts_update_own"
  on public.accounts for update
  using (auth.uid() = user_id);

create policy "accounts_delete_own"
  on public.accounts for delete
  using (auth.uid() = user_id);


-- 3. Attendance Table
create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  account_name text not null,
  date date not null,
  is_present boolean not null,
  created_at timestamptz default now(),
  unique (user_id, account_name, date)
);

create index if not exists idx_attendance_user_account_date
  on public.attendance (user_id, account_name, date);

alter table public.attendance enable row level security;

create policy "attendance_select_own"
  on public.attendance for select
  using (auth.uid() = user_id);

create policy "attendance_insert_own"
  on public.attendance for insert
  with check (auth.uid() = user_id);

create policy "attendance_update_own"
  on public.attendance for update
  using (auth.uid() = user_id);

create policy "attendance_delete_own"
  on public.attendance for delete
  using (auth.uid() = user_id);


-- 4. Hisaab Days Table
create table if not exists public.hisaab_days (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  account_name text not null,
  date date not null,
  created_at timestamptz default now(),
  unique (user_id, account_name, date)
);

create index if not exists idx_hisaab_days_user_account_date
  on public.hisaab_days (user_id, account_name, date);

alter table public.hisaab_days enable row level security;

create policy "hisaab_days_select_own"
  on public.hisaab_days for select
  using (auth.uid() = user_id);

create policy "hisaab_days_insert_own"
  on public.hisaab_days for insert
  with check (auth.uid() = user_id);

create policy "hisaab_days_delete_own"
  on public.hisaab_days for delete
  using (auth.uid() = user_id);


-- 5. Adjustments Table
create table if not exists public.adjustments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  account_name text not null,
  date date not null,
  amount numeric not null,
  note text,
  created_at timestamptz default now()
);

create index if not exists idx_adjustments_user_account
  on public.adjustments (user_id, account_name);

alter table public.adjustments enable row level security;

create policy "adjustments_select_own"
  on public.adjustments for select
  using (auth.uid() = user_id);

create policy "adjustments_insert_own"
  on public.adjustments for insert
  with check (auth.uid() = user_id);

create policy "adjustments_update_own"
  on public.adjustments for update
  using (auth.uid() = user_id);

create policy "adjustments_delete_own"
  on public.adjustments for delete
  using (auth.uid() = user_id);


-- 6. Owner Previous Entries Table (from existing migration)
create table if not exists public.owner_previous_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  account_name text not null,
  date date not null,
  amount numeric not null check (amount > 0),
  kind text not null check (kind in ('received', 'paid')),
  note text,
  created_at timestamptz default now()
);

create index if not exists idx_owner_previous_entries_user_account
  on public.owner_previous_entries (user_id, account_name);

alter table public.owner_previous_entries enable row level security;

create policy "owner_previous_entries_select_own"
  on public.owner_previous_entries for select
  using (auth.uid() = user_id);

create policy "owner_previous_entries_insert_own"
  on public.owner_previous_entries for insert
  with check (auth.uid() = user_id);

create policy "owner_previous_entries_update_own"
  on public.owner_previous_entries for update
  using (auth.uid() = user_id);

create policy "owner_previous_entries_delete_own"
  on public.owner_previous_entries for delete
  using (auth.uid() = user_id);


-- 7. Stock Table
create table if not exists public.stock (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  date date not null,
  type text not null,
  quantity_kg numeric not null,
  remaining_stock_kg numeric not null,
  account_name text,
  vehicle_number text,
  rate_per_quintal numeric,
  total_amount numeric,
  note text,
  transaction_id bigint,
  created_at timestamptz default now()
);

create index if not exists idx_stock_user_id
  on public.stock (user_id);

alter table public.stock enable row level security;

create policy "stock_select_own"
  on public.stock for select
  using (auth.uid() = user_id);

create policy "stock_insert_own"
  on public.stock for insert
  with check (auth.uid() = user_id);

create policy "stock_update_own"
  on public.stock for update
  using (auth.uid() = user_id);

create policy "stock_delete_own"
  on public.stock for delete
  using (auth.uid() = user_id);


-- 8. App Settings Table
create table if not exists public.app_settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  key text not null,
  value jsonb not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (user_id, key)
);

create index if not exists idx_app_settings_user_key
  on public.app_settings (user_id, key);

alter table public.app_settings enable row level security;

create policy "app_settings_select_own"
  on public.app_settings for select
  using (auth.uid() = user_id);

create policy "app_settings_insert_own"
  on public.app_settings for insert
  with check (auth.uid() = user_id);

create policy "app_settings_update_own"
  on public.app_settings for update
  using (auth.uid() = user_id);

create policy "app_settings_delete_own"
  on public.app_settings for delete
  using (auth.uid() = user_id);
