-- Owner-only "previous amounts" (not in transactions table).
-- Run this in the Supabase SQL editor if the table does not exist yet.

create table if not exists public.owner_previous_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  account_name text not null,
  date date not null,
  amount numeric not null check (amount > 0),
  kind text not null check (kind in ('received', 'paid')),
  note text,
  created_at timestamptz default now()
);

create index if not exists idx_owner_previous_entries_user_account
  on public.owner_previous_entries (user_id, account_name);

alter table public.owner_previous_entries enable row level security;

create policy "owner_previous_entries_select_own"
  on public.owner_previous_entries for select
  using (auth.uid() = user_id);

create policy "owner_previous_entries_insert_own"
  on public.owner_previous_entries for insert
  with check (auth.uid() = user_id);

create policy "owner_previous_entries_update_own"
  on public.owner_previous_entries for update
  using (auth.uid() = user_id);

create policy "owner_previous_entries_delete_own"
  on public.owner_previous_entries for delete
  using (auth.uid() = user_id);
